baseURL = "https://algo-afro-futures.lurk.org/"
languageCode = "en-us"
title = "(Algo|Afro) Futures"
theme = "hugo-researcher"

[params]
  author = "(Algo|Afro) Futures"
  description = "(Algo|Afro) Futures is a mentoring programme for early career Black artists who want to explore creative coding and live coding."
  favicon = "favicon.ico"  # path to a .ico to use as favicon
  logo = "/banner.png"
  
[params.style]  # appearance options (can be omitted)

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 2
  [[menu.main]]
    name = "Apply"
    url = "/apply"
    weight = 3
  [[menu.main]]
    name = "FAQ"
    url = "/faq"
    weight = 4
  [[menu.main]]
    name = "2021"
    url = "/2021-programme/"
    weight = 5
  [[menu.main]]
    name = "2022"
    url = "/2022-programme/"
    weight = 6
  [[menu.main]]
    name = "2023"
    url = "/2023-programme/"
    weight = 7
  [[menu.main]]
    name = "2025"
    url = "/2025-programme/"
    weight = 8
[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files
  
[permalinks]
  "/" = "/:filename"
